baseURL = "https://libnull.com/"
theme = 'lynx'
languageCode = 'zh-cn'
title = '4679'
copyright = " "
disableKinds = ["page", "section", "RSS", "sitemap", "404", "taxonomy", "term"]
[params]
  attribution = false

[author]
  name = "4679"
  headline = "FF14鸟区玩家"
  image = "https://gravatar.webp.se/avatar/9787362c7b4fce655bff66d858903a12?s=256"

  links = [
    { email = "mailto:admin@libnull.com" },
    { telegram = "https://t.me/Anaesthesine" },
    { twitter = "https://twitter.com/AnaAnaxiv" },
    { github = "https://github.com/4679" },
    { steam = "https://steamcommunity.com/id/4679" },
    { link = { href = "https://aur.archlinux.org/account/4679", text = "AUR" } },
    { link = { href = "https://www.acfun.cn/u/408177", text = "AcFun" } },
    { link = { href = "https://www.xivmodarchive.com/user/200944", text = "XMA" } },
    { link = { href = "https://gist.github.com/4679/84e2d0557aba27fdd9ddd3901db17169", text = "PC Specs" } },
  ]
